//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tester
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class TestAbstractFactory
	{
		public virtual Host Host
		{
			get;
			set;
		}

		public abstract void CreateTest();

	}
}

