//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tester
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	internal class TestProduct_ICMP : ITestProduct
	{

	    private string _IPAddress;
        

	    public TestProduct_ICMP(string IPAddress)
	    {
	        _IPAddress = IPAddress;

	    }


        public bool Check()
        {
            Console.WriteLine("Send ping on " + _IPAddress);
            return true;
        }
    }
}

